### ISSUE TITLE
Support for other version formats

### ISSUE THREAD

**Issue by elliotchance** [keleshev/version#3]
Need to support other formats:

* `1.2` -> `1.2.0`
* `2` -> `2.0.0`

Also there may be an optional `v` as a prefix like `v1.2.3`

**Comment by keleshev** [comment]
This project's aim is limited to supporting [Semantic Versioning specification](http://semver.org/). And I personally believe that it's beneficial for all developers if we stick to a single well-defined format.

**Comment by elliotchance** [comment]
Fair enough, and it makes sense that the existing applications throw a `VersionError` for invalid semantic versions. However, anyone trying to use this library with existing versions (like myself on PyPI) it's pretty much useless because many of the versions do not follow the strict standard. This doesn't means the versions are invalid or translatable to semantic versions.

How about an explicit option on the constructor?

```python
version = Version('1.0', enforce_semantic=False)
print version
# 1.0.0
```

Or if you don't want to pollute the constructor, maybe another factory method?

```python
version = Version.interpret('1.0')
```

For my case, I had to do this:

https://github.com/elliotchance/ovum/blob/223312e5085520228d690979fff561662dfaabde/ovum.py#L22
https://github.com/elliotchance/ovum/blob/223312e5085520228d690979fff561662dfaabde/test_ovum.py#L116

Either way it would be a great benefit if your library could handle more version formats.

**Comment by keleshev** [comment]
There was a PEP and a library that was introduced specifically for this purpose, but I can't find it right now.
